### ISSUE TITLE
Error with cleanup-openhab-influxdb2.sh

### ISSUE THREAD

**Issue by TheNavy** [alaub81/openHAB#1]
The OpenHAB -> InfluxDB Cleanup script won't work for me:

`awk: fatal: invalid regexp: Invalid regular expression: /"values":[/`

I've changed the following line
`awk -F '"values":\[' '{ print $2 }' |\`
to
`awk -F '"values":' '{ print $2 }' |\`

and now it finished perfectly without error and deletes the correct Measurements :)

**Comment by alaub81** [comment]
I can not reproduce your problem. On my environment everything is working, but also with your change. I will play around a bit, and if your change is working fine, I will update the script!

**Comment by alaub81** [comment]
After checking the proposed fix, I changed it to:

`awk -F '"values":' '{ print $2 }' |\`

there is no difference of the output.
