### ISSUE TITLE
Tutorial Issues

### ISSUE THREAD

**Issue by Pazze12** [alaub81/openHAB#2]
Hallo, erstmal vielen dank für das gute Tutorial:
https://www.laub-home.de/wiki/OpenHAB_3_Docker_Installation

Jedoch stoße ich auf einige Fehler:
Der User ->  Read Only User (openhab_ro) wurde nie angelegt. Es würde nie erklärt bzw gezeigt, kann ich es im nachhinein noch machen ohne neuzustarten?

Es wird immer von InfluxDB 1 und 2 gesprochen aber ich kann nur eins auswählen die werte bleiben gleich.

Ich hbe mein deployment glaube ich eins zu eins wie im tutorial befolgt und nur dann was geändert wenn es auch da stand.

Haben sie einen Tipp für mich?

**Comment by Pazze12** [comment]
problem eins habe ich so gelöst:

```
docker exec openhab3_influxdb_1 influx user create -n openhab_ro -p <password> -o myorg
```

**Comment by Pazze12** [comment]
Bekomme COMMUNICATION_ERROR
CONNECT failed as CONNACK contained an Error Code: NOT_AUTHORIZED.
vom mosquitto ;/

**Comment by alaub81** [comment]
Hallo @Pazze12 ,

welche InfluxDB Version wurde denn in der .env konfiguriert? In meinem Tutorial verwende ich mittlerweile InfluxDB in Version 2.x. Hier wird die ganze Authentifizierung via API Token geregelt. 
Ich werde auf jeden Fall nun alles zum Thema Version 1.x aus dem Tutorial entfernen, da ich denke, das es mittlerweile eh obsolete ist die V 1 einzusetzen.

Falls du noch mehr Fragen hast, lass es mich gerne wissen.

**Comment by Pazze12** [comment]
Ah ok , oh man ich dachte die ganze Zeit es handelt sich um zwei Datenbanken.
Genau ich nutze auch die Version 2

Heute Abend teste ich weiter, ich versuche mich an meiner ersten Haussteuerung.
Ich muss heute noch schauen warum ich keinen Zugriff auf mosquitto bekomme obwohl ich mit dem docker-compose exec Befehl mein Passwort geändert habe.
