### ISSUE TITLE
Kein Beispiel in den Scripten wie man das .sh file ausführen soll

### ISSUE THREAD

**Issue by martin8310** [alaub81/openHAB#3]
Hallo, 

das sind ja tolle Scripte, danke dafür. 

1. Anmerkung meiner Seits: Es wäre für Anfänger hilfreich, wenn ein Beispiel im Script auch aufgeführt werden würde, wie der code in der Kommandozeile einzugeben ist, so wie es auf deiner Homepage ist!

2. `drop "DHT22_Temperature"` funktioniert nicht, es sollte `DROP MEASUREMENT "DHT22_Temperature"` heißen, denke ich.
Die Hochkommas sind wichtig, da sie dann bei solchen Werte Namen wie `Smartmeter/Q3D_AVG1min` auch funktionieren.
Denke die Hochkommas sollten auch in die Scripte rein.

Gruß und Dank
Martin

Beispiel auf deiner Seite:

```
wie immer dem Script das Execute rechte geben:
chmod +x /usr/local/sbin/rename-influxdb-measurement.sh
Dann das Script einfach starten, in dem man ihm den Alten Measurement Namen gibt und darauf gefolgt den Neuen Measurement Namen:

/usr/local/sbin/rename-influxdb-measurement.sh { OldMeasurementName } { NewMeasurementName }
# Beispiel
rename-influxdb-measurement.sh DHT22Temperature DHT22Temperature1
```

**Comment by alaub81** [comment]
Hi @martin8310,

Danke für dein feedback! 

Zu 1. : Ich gehe davon aus, dass du hier in GitHub die README.md meinst, die ergänzt werden sollte? Oder im Info Header jedes Scripts?

Zu 2. : Um welches Script handelt es sich denn? Bei den Hochkommas gebe ich dir recht. Allerdings müsste ich das erst einmal testen. ich denke da müsste eine Kombination von '' und "" herhalten.

Grüße
Andreas

**Comment by martin8310** [comment]
Hallo Andreas,

zu 1. Ich dachte da an jedes Script. Da ich jetzt ein Beispiel für das Script "rename-influxdb-measurement.sh" gefunden habe, ist das kein Problem mehr. Das Scrip "delete-wrong-influxdb-measurements.sh" würde ich auch gerne benutzen, weiß aber nicht ob ich den Namen und den Wert im Script ändern muss, oder ob ich es beim aufrufen in der Kommandozeile eingeben kann.

Zu 2. beim "delete-wrong-influxdb-measurements.sh" zum Beispiel. Da muss "INFLUXDBMEASUREMENT" ja deklariert werden.

Gruß
Martin

**Comment by alaub81** [comment]
OK, verstanden. Die Script waren tatsächlich gar nicht unbedingt dafür gedacht, dass ich sie so gut dokumentiere. Der Code ist die Doku :-) Aber verstehe natürlich dein Anliegen.

Was ich dir aber direkt sagen kann, bei "delete-wrong-influxdb-measurements.sh" musst du die Variablen im Script anpassen.

Wenn ich die Tage mal zeit habe, versuche ich die Script etwas zu vereinheitlichen und Hinweise zu geben, wie sie bedient werden können.
