### ISSUE TITLE
Deployment error from networks

### ISSUE THREAD

**Issue by wildcs** [alaub81/openHAB#4]
Hi,
i tried to use your yaml to setup openhab with my portainer installation but i can't deploy the stack:

`Ignoring unsupported options: network_mode, restart failed to create service openhab_grafana: Error response from daemon: The network openhab_app-nw cannot be used with services. Only networks scoped to the swarm can be used, such as those created with the overlay driver. `

`Ignoring unsupported options: network_mode, restart failed to create service openhab_mosquitto: Error response from daemon: The network openhab_app-nw cannot be used with services. Only networks scoped to the swarm can be used, such as those created with the overlay driver. `

`Ignoring unsupported options: network_mode, restart failed to create service openhab_postgres: Error response from daemon: The network openhab_backend-nw cannot be used with services. Only networks scoped to the swarm can be used, such as those created with the overlay driver. `

Using docker 24.0.7 and portainer 2.19.4 on a debian 12 vmm

**Comment by wildcs** [comment]
Okay forget it. Don't know why but my docker was installed in swarm-mode.
I had to leave the swarm to get it working `docker swarm leave --force.` Thank you for your manual 👍

**Comment by alaub81** [comment]
Nice to hear that :-D

I will close the issue
